name: Build and deploy master

on:
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - name: Set up JDK 1.17
        uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1.4.4
        with:
          java-version: 1.17

      - name: git config
        run: |
          git config --global user.name "Monumenta CI"
          git config --global user.email "Monumenta.CI@NotARealEmail.com"

      - name: Cache maven dependencies
        uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        env:
          cache-name: cache-maven-dependencies
        with:
          # maven files are stored in `~/.m2/repository`
          path: |
            ~/.m2/repository
            ~/.gradle/caches
            ~/.gradle/wrapper
          # Create the key based on runner os, cache name, and a hash of all the pom.xml files
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build and deploy to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew publish
