name: Pull request CI

on: [pull_request]

jobs:
  build:
    name: Build plugin
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - name: Set up JDK 1.17
        uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1.4.4
        with:
          java-version: 1.17

      - name: Setup reviewdog
        uses: reviewdog/action-setup@3f401fe1d58fe77e10d665ab713057375e39b887 # v1.3.0
        with:
          reviewdog_version: latest

      - name: git config
        run: |
          git config --global user.name "Monumenta CI"
          git config --global user.email "Monumenta.CI@NotARealEmail.com"

      - name: Cache maven dependencies
        uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        env:
          cache-name: cache-maven-dependencies
        with:
          # maven files are stored in `~/.m2/repository`
          path: |
            ~/.m2/repository
            ~/.gradle/caches
            ~/.gradle/wrapper
          # Create the key based on runner os, cache name, and a hash of all the pom.xml files
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build and report style/pmd/warnings
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -o pipefail
          ./gradlew build --console=plain | tee compile.log
          set +o pipefail
          cat compile.log | grep '^\[WARNING\].*\.java' | reviewdog -efm="[WARNING] %f:[%l,%c] %m" -name="compiler-warnings" -reporter=github-pr-check
          cat ./plugin/build/reports/checkstyle/main.xml | reviewdog -f=checkstyle -name="checkstyle (plugin)" -reporter=github-pr-check
          cat ./plugin/build/reports/pmd/main.xml | reviewdog -efm='%+P<file name="%f">' -efm='%W<violation beginline="%l%.%#begincolumn="%c%.%#' -efm='%-C<%.%#' -efm='%+C%.%#' -efm='%-Q' -name="pmd" -reporter=github-pr-check
